/*
 * Weather API
 *
 *  # Introduction  WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy.    We provide following data through our API:     - Real-time weather - 14 day weather forecast - Astronomy - Time zone - Location data - Search or Autocomplete API - NEW: Historical weather - NEW: Future Weather (Upto 300 days ahead) - Weather Alerts - Air Quality Data  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!    We have [code libraries](https://www.weatherapi.com/docs/code-libraries.aspx) for different programming languages like PHP, .net, JAVA, etc.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.  Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=<YOUR API KEY>  
 *
 * API version: 1.0.0-oas3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ForecastHour struct {
	TimeEpoch int32 `json:"time_epoch,omitempty"`
	Time string `json:"time,omitempty"`
	TempC float64 `json:"temp_c,omitempty"`
	TempF float64 `json:"temp_f,omitempty"`
	IsDay int32 `json:"is_day,omitempty"`
	Condition *ForecastCondition `json:"condition,omitempty"`
	WindMph float64 `json:"wind_mph,omitempty"`
	WindKph float64 `json:"wind_kph,omitempty"`
	WindDegree int32 `json:"wind_degree,omitempty"`
	WindDir string `json:"wind_dir,omitempty"`
	PressureMb int32 `json:"pressure_mb,omitempty"`
	PressureIn float64 `json:"pressure_in,omitempty"`
	PrecipMm int32 `json:"precip_mm,omitempty"`
	PrecipIn int32 `json:"precip_in,omitempty"`
	Humidity int32 `json:"humidity,omitempty"`
	Cloud int32 `json:"cloud,omitempty"`
	FeelslikeC float64 `json:"feelslike_c,omitempty"`
	FeelslikeF float64 `json:"feelslike_f,omitempty"`
	WindchillC float64 `json:"windchill_c,omitempty"`
	WindchillF float64 `json:"windchill_f,omitempty"`
	HeatindexC float64 `json:"heatindex_c,omitempty"`
	HeatindexF float64 `json:"heatindex_f,omitempty"`
	DewpointC float64 `json:"dewpoint_c,omitempty"`
	DewpointF float64 `json:"dewpoint_f,omitempty"`
	WillItRain int32 `json:"will_it_rain,omitempty"`
	ChanceOfRain int32 `json:"chance_of_rain,omitempty"`
	WillItSnow int32 `json:"will_it_snow,omitempty"`
	ChanceOfSnow int32 `json:"chance_of_snow,omitempty"`
	VisKm int32 `json:"vis_km,omitempty"`
	VisMiles int32 `json:"vis_miles,omitempty"`
	GustMph int32 `json:"gust_mph,omitempty"`
	GustKph float64 `json:"gust_kph,omitempty"`
	Uv int32 `json:"uv,omitempty"`
}
