/*
 * Weather API
 *
 *  # Introduction  WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy.    We provide following data through our API:     - Real-time weather - 14 day weather forecast - Astronomy - Time zone - Location data - Search or Autocomplete API - NEW: Historical weather - NEW: Future Weather (Upto 300 days ahead) - Weather Alerts - Air Quality Data  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!    We have [code libraries](https://www.weatherapi.com/docs/code-libraries.aspx) for different programming languages like PHP, .net, JAVA, etc.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.  Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=<YOUR API KEY>  
 *
 * API version: 1.0.0-oas3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ForecastDay struct {
	MaxtempC float64 `json:"maxtemp_c,omitempty"`
	MaxtempF float64 `json:"maxtemp_f,omitempty"`
	MintempC float64 `json:"mintemp_c,omitempty"`
	MintempF float64 `json:"mintemp_f,omitempty"`
	AvgtempC float64 `json:"avgtemp_c,omitempty"`
	AvgtempF float64 `json:"avgtemp_f,omitempty"`
	MaxwindMph float64 `json:"maxwind_mph,omitempty"`
	MaxwindKph float64 `json:"maxwind_kph,omitempty"`
	TotalprecipMm int32 `json:"totalprecip_mm,omitempty"`
	TotalprecipIn int32 `json:"totalprecip_in,omitempty"`
	AvgvisKm int32 `json:"avgvis_km,omitempty"`
	AvgvisMiles int32 `json:"avgvis_miles,omitempty"`
	Avghumidity int32 `json:"avghumidity,omitempty"`
	DailyWillItRain int32 `json:"daily_will_it_rain,omitempty"`
	DailyChanceOfRain int32 `json:"daily_chance_of_rain,omitempty"`
	DailyWillItSnow int32 `json:"daily_will_it_snow,omitempty"`
	DailyChanceOfSnow int32 `json:"daily_chance_of_snow,omitempty"`
	Condition *ForecastDayCondition `json:"condition,omitempty"`
	Uv int32 `json:"uv,omitempty"`
}
