/*
 * Weather API
 *
 * # Introduction WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy. We provide following data through our API:     - Real-time weather - 14 day weather forecast - Historical Weather - Marine Weather and Tide Data - Future Weather (Upto 365 days ahead) - Daily and hourly intervals - 15 min interval (Enterprise only) - Astronomy - Time zone - Location data - Sports - Search or Autocomplete API - Weather Alerts - Air Quality Data - Bulk Request  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!  Try our weather API by using interactive [API Explorer](https://www.weatherapi.com/api-explorer.aspx).  We also have SDK for popular framework/languages available on [Github](https://github.com/weatherapicom/) for quick integrations.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.    Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=YOUR API KEY  
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ForecastDay struct {
	MaxtempC float32 `json:"maxtemp_c,omitempty"`
	MaxtempF float32 `json:"maxtemp_f,omitempty"`
	MintempC float32 `json:"mintemp_c,omitempty"`
	MintempF float32 `json:"mintemp_f,omitempty"`
	AvgtempC float32 `json:"avgtemp_c,omitempty"`
	AvgtempF float32 `json:"avgtemp_f,omitempty"`
	MaxwindMph float32 `json:"maxwind_mph,omitempty"`
	MaxwindKph float32 `json:"maxwind_kph,omitempty"`
	TotalprecipMm float32 `json:"totalprecip_mm,omitempty"`
	TotalprecipIn float32 `json:"totalprecip_in,omitempty"`
	AvgvisKm float32 `json:"avgvis_km,omitempty"`
	AvgvisMiles float32 `json:"avgvis_miles,omitempty"`
	Avghumidity float32 `json:"avghumidity,omitempty"`
	DailyWillItRain int32 `json:"daily_will_it_rain,omitempty"`
	DailyChanceOfRain float32 `json:"daily_chance_of_rain,omitempty"`
	DailyWillItSnow int32 `json:"daily_will_it_snow,omitempty"`
	DailyChanceOfSnow float32 `json:"daily_chance_of_snow,omitempty"`
	Condition *ForecastDayCondition `json:"condition,omitempty"`
	Uv int32 `json:"uv,omitempty"`
}
